### PR TITLE
Fix Chinese translation; closes #10

### LINKED ISSUE #10: Apparently chinese translation of this mod is wrong
Heroes skills descriptions apparently do not match what they do. Reported by user to me on... Steam :P

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

I confirm there were wrong information in the Chinese translation, probably due to town updates. I have also fixed some French translations.

@by003, can you proofread?

### CODE REVIEW

**Comment by by003** [comment]
I will do it when I am free. I am now finished all Chinese translation in vcmi-mods

**Comment by by003** [comment]
@misiokles  I have updated Chinese language in menu, could you help me to upload it into pull request?
[chinese.zip](https://github.com/vcmi-mods/retreat-town/files/12803339/chinese.zip)

**Comment by misiokles** [comment]
actually I don't know. @dydzio0614 is the best person to explain how to add local translations to vcmi code.

**Comment by dydzio0614** [comment]
you probably mean @IvanSavenko  :P

**Comment by Fabrice-TIERCELIN** [comment]
[Done](https://github.com/vcmi/vcmi/pull/3007)

**Comment by Fabrice-TIERCELIN** [comment]
@by003, can you confirm this Chinese translation is accurate?
- English: _"Mark of Eminence allows to recruit Silver Dragons."_
- Chinese: _"高级卓越标志允许招募银龙。"_

**Comment by by003** [comment]
This is not an accurate Chinese translation, so do not use google translation.
I think in Chinese context, it should be:
English: "Mark of Eminence" 
Chinese: "山灵印记”
English: "Mark of Eminence allows to recruit Silver Dragons."
Chinese: "高级山灵印记允许招募银龙。"

**Pull request merged**
